[package]
name = "imagen-duplicada"
version = "0.1.4"
description = "Detector de imágenes duplicadas"
edition = "2021"

[lib]
name = "imagen_duplicada_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
sha2 = "0.10"
kamadak-exif = "0.5"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif", "tiff", "bmp"] }
trash = "5"
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1"
rayon = "1.10"
memmap2 = "0.9"

[profile.release]
strip = true
lto = true
opt-level = "s"
panic = "abort"
